export const bestSellersLists: Record<string, { id: number; name: string; updated: string }> = {
  CombinedPrintAndEBookFiction: { id: 704, name: "Combined Print & E-Book Fiction", updated: "WEEKLY" },
  CombinedPrintAndEBookNonfiction: { id: 708, name: "Combined Print & E-Book Nonfiction", updated: "WEEKLY" },
  HardcoverFiction: { id: 1, name: "Hardcover Fiction", updated: "WEEKLY" },
  HardcoverNonfiction: { id: 2, name: "Hardcover Nonfiction", updated: "WEEKLY" },
  PaperbackTradeFiction: { id: 17, name: "Paperback Trade Fiction", updated: "WEEKLY" },
  PaperbackNonfiction: { id: 4, name: "Paperback Nonfiction", updated: "WEEKLY" },
  AdviceHowToMiscellaneous: { id: 24, name: "Advice, How-To & Miscellaneous", updated: "WEEKLY" },
  ChildrensMiddleGradeHardcover: { id: 13, name: "Children’s Middle Grade Hardcover", updated: "WEEKLY" },
  ChildrensPictureBooks: { id: 7, name: "Children’s Picture Books", updated: "WEEKLY" },
  ChildrensSeries: { id: 10, name: "Children’s Series", updated: "WEEKLY" },
  YoungAdultHardcover: { id: 14, name: "Young Adult Hardcover", updated: "WEEKLY" },
  AudioFiction: { id: 301, name: "Audio Fiction", updated: "MONTHLY"},
  AudioNonFiction: { id: 301, name: "Audio Nonfiction", updated: "MONTHLY"},
  BusinessBooks: { id: 532, name: "Business Books", updated: "MONTHLY"},
  GraphicBooksandManga: { id: 719, name: "Graphic Books and Manga", updated: "MONTHLY"},
  MassMarket: { id: 10018, name: "Mass Market", updated: "MONTHLY" },
  MiddleGradePaperback: { id: 10015, name: "Middle Grade Paperback", updated: "MONTHLY" },
  YoungAdultPaperback: { id: 10016, name: "Young Adult Paperback", updated: "MONTHLY" },
};